name: generate android 13 image

on:
  workflow_dispatch:

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Build image
      run: |
            cd emulator && echo 2000 | ./automate_android.sh ../conf/android-13;
            docker images;
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_ACTOR }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - 
      name: Push to Docker Hub
      run: |
            docker image tag android-emulator:android-13 dzhunli/android-emulator:android-13
            docker push dzhunli/android-emulator:android-13
