name: generate android 13 image

on:
  workflow_dispatch:

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_ACTOR }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build image
      run: |
            cd emulator && echo 2000 | ./automate_android.sh ../conf/android-13;
            docker images;
    -
      name: Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: android-emulator:android-13        
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
    -
      name: Auto analyze image
      run: |
        DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/');
        curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb;
        sudo apt install ./dive_${DIVE_VERSION}_linux_amd64.deb;
        CI=true dive --ci-config .dive-ci.yml android-emulator:android-13 

    - 
      name: Push to Docker Hub
      run: |
            docker image tag android-emulator:android-13 dzhunli/android-emulator:android-13
            docker push dzhunli/android-emulator:android-13
