name: make android images

on:
  push:
    branches: [ "main" ]

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Build image
    - uses: actions/checkout@v4
      run: |
       cd emulator && echo 2000 | ./automate_android.sh ../conf/android-13;
       docker images;

    - name: Login to Docker Hub
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_ACTOR }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
