name: generate android 13 image

on:
  workflow_dispatch:

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_ACTOR }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build Docker Image
      run: |
            echo -e "\n"
            echo "::group::building docker image" 
            cd emulator && echo 2000 | ./automate_android.sh ../conf/android-13;
            echo "::endgroup::"
    -
        name: Run Dive Analysis
        uses: dzhunli/image-analytics@v2-staging
        with:
          image_name: "android-emulator:android-13"
          ci_config: ".dive-ci.yml"
#          allow_large_image: "true"
    #-
    #  name: Analyze Docker Image
    #  run: |
    #        CI=true dive --ci-config .dive-ci.yml android-emulator:android-13 
    -
      name: Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: android-emulator:android-13        
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
    - 
      name: Push to Docker Hub
      run: |
            docker image tag android-emulator:android-13 dzhunli/android-emulator:android-13
            docker push dzhunli/android-emulator:android-13
