name: make android images

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: |
       cd emulator && echo 2000 | ./automate_android.sh ../conf/android-13;
       echo "Action done"
